name = "DeepLearningKoans"
uuid = "a24de3d4-3d97-59d4-a72b-9f03e664510d"
authors = ["Adam Wespiser <adamwespiser@gmail.com>"]
version = "0.0.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[compat]
julia = "1.1"
